# Netlify Configuration
[build]
  publish = "."
  functions = "netlify/functions"

# Redirect rules for the chat API
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (configure in Netlify dashboard)
# BLACKBOX_API_KEY = "your-api-key-here"
