// Projects data - Auto-generated by incremental-sync.js
// Last updated: 2025-10-24T19:34:26.489Z
// Total projects: 16

const projects = [
  {
    "name": "website",
    "title": "Personal Portfolio Website",
    "description": "Showcases projects, skills, and experience as a Software & AI Prompt Engineer.",
    "date": "NaN",
    "image": "images/projects/website.webp",
    "topics": [
      "JavaScript",
      "CSS",
      "HTML",
      "web"
    ],
    "html_url": "https://github.com/gderamchi/website",
    "homepage": null,
    "stars": 0,
    "language": "JavaScript",
    "updated": "2025-10-24T19:34:26.488Z"
  },
  {
    "name": "startup-idea",
    "title": "AI Feedback to Task Converter",
    "description": "Transforms creative feedback into tasks, cutting revision time by 50%.",
    "date": "2025",
    "image": "images/projects/startup-idea.webp",
    "topics": [
      "Python",
      "Makefile",
      "TypeScript"
    ],
    "html_url": "https://github.com/gderamchi/startup-idea",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-10-24T03:11:06Z"
  },
  {
    "name": "hackathonblackbox42",
    "title": "AI Code Review Bot",
    "description": "Automates code analysis and bug detection with interactive AI support.",
    "date": "2025",
    "image": "images/projects/hackathonblackbox42.webp",
    "topics": [
      "Python",
      "Shell",
      "ai"
    ],
    "html_url": "https://github.com/gderamchi/hackathonblackbox42",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-10-23T20:43:33Z"
  },
  {
    "name": "portfolio-florid",
    "title": "Art Portfolio Showcase",
    "description": "A modern React site displaying an art student's creations.",
    "date": "2025",
    "image": "images/projects/portfolio-florid.webp",
    "topics": [
      "TypeScript",
      "CSS",
      "HTML",
      "web"
    ],
    "html_url": "https://github.com/gderamchi/portfolio-florid",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-06-27T23:27:42Z"
  },
  {
    "name": "eugeniackathon",
    "title": "Slack Workflow Automation",
    "description": "Automates Slack tasks using webhooks and an AI agent.",
    "date": "2025",
    "image": "images/projects/eugeniackathon.webp",
    "topics": [],
    "html_url": "https://github.com/gderamchi/eugeniackathon",
    "homepage": null,
    "stars": 0,
    "language": "Unknown",
    "updated": "2025-06-04T04:21:30Z"
  },
  {
    "name": "presence-pulse-events",
    "title": "Real-Time Event Presence Tracker",
    "description": "Monitors and updates event attendance in real-time.",
    "date": "2025",
    "image": "images/projects/presence-pulse-events.webp",
    "topics": [
      "TypeScript",
      "CSS",
      "HTML"
    ],
    "html_url": "https://github.com/Moulaye-Samake24/presence-pulse-events",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-06-03T03:26:08Z"
  },
  {
    "name": "hackathon_doctolib",
    "title": "AI Pathology Copilot",
    "description": "Enhances healthcare diagnostics using AI for pathology insights.",
    "date": "2025",
    "image": "images/projects/hackathon_doctolib.webp",
    "topics": [
      "ai",
      "aiagent",
      "backend",
      "doctolib",
      "front-end-development",
      "genai",
      "healthcare",
      "portfolio-featured"
    ],
    "html_url": "https://github.com/gderamchi/hackathon_doctolib",
    "homepage": null,
    "stars": 2,
    "language": "Python",
    "updated": "2025-06-02T10:32:22Z"
  },
  {
    "name": "telecomParisHackathon",
    "title": "Cardiac Toxicity Predictor",
    "description": "Predicts cardiac toxicity using SMILES data, enhancing drug safety assessments.",
    "date": "2025",
    "image": "images/projects/telecomParisHackathon.webp",
    "topics": [
      "Python",
      "Shell",
      "Dockerfile"
    ],
    "html_url": "https://github.com/gderamchi/telecomParisHackathon",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-05-25T20:07:57Z"
  },
  {
    "name": "truth-stake-social",
    "title": "Social Media Truth Verification Tool",
    "description": "Verifies facts on social media to combat misinformation.",
    "date": "2025",
    "image": "images/projects/truth-stake-social.webp",
    "topics": [
      "TypeScript",
      "CSS",
      "HTML"
    ],
    "html_url": "https://github.com/gderamchi/truth-stake-social",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-05-18T11:41:34Z"
  },
  {
    "name": "creditmanagement",
    "title": "Smart Construction Assistant",
    "description": "AI tool for organizing and analyzing construction project emails.",
    "date": "2025",
    "image": "images/projects/creditmanagement.webp",
    "topics": [
      "JavaScript",
      "HTML"
    ],
    "html_url": "https://github.com/gderamchi/creditmanagement",
    "homepage": null,
    "stars": 0,
    "language": "JavaScript",
    "updated": "2025-04-05T13:16:32Z"
  },
  {
    "name": "docagent",
    "title": "Document Automation Platform",
    "description": "Automates document processing with NLP and generation capabilities.",
    "date": "2025",
    "image": "images/projects/docagent.webp",
    "topics": [
      "TypeScript",
      "Python",
      "Shell"
    ],
    "html_url": "https://github.com/gderamchi/docagent",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-03-18T14:39:56Z"
  },
  {
    "name": "2024-2025-project-3-quickest-path-team-7",
    "title": "Optimal Route Finder",
    "description": "Calculates the quickest path for efficient travel.",
    "date": "2025",
    "image": "images/projects/2024-2025-project-3-quickest-path-team-7.webp",
    "topics": [
      "portfolio-featured",
      "C++",
      "JavaScript",
      "CSS"
    ],
    "html_url": "https://github.com/algosup/2024-2025-project-3-quickest-path-team-7",
    "homepage": null,
    "stars": 4,
    "language": "C++",
    "updated": "2025-02-25T11:24:47Z"
  },
  {
    "name": "GenAI_hackaton",
    "title": "Automated Client Profile Generator",
    "description": "Web app automating client profile creation using public data.",
    "date": "2025",
    "image": "images/projects/GenAI_hackaton.webp",
    "topics": [
      "Python",
      "CSS",
      "JavaScript"
    ],
    "html_url": "https://github.com/GuillotSamuel/GenAI_hackaton",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-02-04T09:27:57Z"
  },
  {
    "name": "2023-2024-project-3-virtual-processor-team-2",
    "title": "Virtual Processor Simulator",
    "description": "Simulates processor functions to optimize assembly code.",
    "date": "2024",
    "image": "images/projects/2023-2024-project-3-virtual-processor-team-2.webp",
    "topics": [
      "aop",
      "aop-interpreter",
      "asm",
      "assembly",
      "at2",
      "iat2",
      "interpreter",
      "language-model"
    ],
    "html_url": "https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2",
    "homepage": null,
    "stars": 8,
    "language": "C",
    "updated": "2025-09-25T10:23:22Z"
  },
  {
    "name": "hackaton-blockchain-vierzon-2024",
    "title": "Blockchain Hackathon Platform",
    "description": "Facilitates blockchain-based hackathon events.",
    "date": "2024",
    "image": "images/projects/hackaton-blockchain-vierzon-2024.webp",
    "topics": [
      "JavaScript",
      "HTML",
      "Solidity"
    ],
    "html_url": "https://github.com/0xBelnadris/hackaton-blockchain-vierzon-2024",
    "homepage": null,
    "stars": 0,
    "language": "JavaScript",
    "updated": "2024-10-06T19:12:27Z"
  },
  {
    "name": "2023-2024-project-5-flutter-team-1",
    "title": "Candidate Adoption App",
    "description": "Connects users with political candidates for engagement and support.",
    "date": "2024",
    "image": "images/projects/2023-2024-project-5-flutter-team-1.webp",
    "topics": [
      "Dart",
      "C++",
      "CMake",
      "web",
      "mobile",
      "app"
    ],
    "html_url": "https://github.com/algosup/2023-2024-project-5-flutter-team-1",
    "homepage": null,
    "stars": 1,
    "language": "Dart",
    "updated": "2024-06-20T20:00:34Z"
  }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { projects };
}
