// Projects data - Auto-generated by sync-portfolio.js
// Last updated: 2025-10-24T00:18:30.892Z
// Total projects: 16

const projects = [
  {
    "name": "hackathonblackbox42",
    "title": "AI-Based Code Review Bot",
    "description": {
      "en": "An intelligent bot for automated code review and bug detection with security scanning.",
      "fr": "An intelligent bot for automated code review and bug detection with security scanning."
    },
    "date": "2025",
    "image": "src/assets/images/projects/hackathonblackbox42.webp",
    "topics": [
      "Python",
      "Shell",
      "ai"
    ],
    "html_url": "https://github.com/gderamchi/hackathonblackbox42",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-10-23T20:43:33Z"
  },
  {
    "name": "website",
    "title": "Personal Portfolio Website",
    "description": {
      "en": "A comprehensive showcase of my skills, projects, and experience in Software & AI Engineering.",
      "fr": "A comprehensive showcase of my skills, projects, and experience in Software & AI Engineering."
    },
    "date": "2025",
    "image": "src/assets/images/projects/website.webp",
    "topics": [
      "JavaScript",
      "CSS",
      "HTML",
      "web"
    ],
    "html_url": "https://github.com/gderamchi/website",
    "homepage": null,
    "stars": 0,
    "language": "JavaScript",
    "updated": "2025-10-12T17:56:07Z"
  },
  {
    "name": "portfolio-florid",
    "title": "Artistic Portfolio Showcase",
    "description": {
      "en": "A modern and elegant React website to display an art student's creations.",
      "fr": "A modern and elegant React website to display an art student's creations."
    },
    "date": "2025",
    "image": "src/assets/images/projects/portfolio-florid.webp",
    "topics": [
      "TypeScript",
      "CSS",
      "HTML",
      "web"
    ],
    "html_url": "https://github.com/gderamchi/portfolio-florid",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-06-27T23:27:42Z"
  },
  {
    "name": "eugeniackathon",
    "title": "Automated Workflow with Slack Integration",
    "description": {
      "en": "Streamlines tasks through a JSON workflow and Slack webhooks for efficient project management.",
      "fr": "Streamlines tasks through a JSON workflow and Slack webhooks for efficient project management."
    },
    "date": "2025",
    "image": "src/assets/images/projects/eugeniackathon.webp",
    "topics": [],
    "html_url": "https://github.com/gderamchi/eugeniackathon",
    "homepage": null,
    "stars": 0,
    "language": "Unknown",
    "updated": "2025-06-04T04:21:30Z"
  },
  {
    "name": "presence-pulse-events",
    "title": "Real-Time Event Presence Tracker",
    "description": {
      "en": "Tracks and analyzes real-time event attendance data.",
      "fr": "Tracks and analyzes real-time event attendance data."
    },
    "date": "2025",
    "image": "src/assets/images/projects/presence-pulse-events.webp",
    "topics": [
      "TypeScript",
      "CSS",
      "HTML"
    ],
    "html_url": "https://github.com/Moulaye-Samake24/presence-pulse-events",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-06-03T03:26:08Z"
  },
  {
    "name": "hackathon_doctolib",
    "title": "AI Pathology Assistant",
    "description": {
      "en": "An AI system assisting in medical pathology, improving healthcare efficiency.",
      "fr": "An AI system assisting in medical pathology, improving healthcare efficiency."
    },
    "date": "2025",
    "image": "src/assets/images/projects/hackathon_doctolib.webp",
    "topics": [
      "ai",
      "aiagent",
      "backend",
      "doctolib",
      "front-end-development",
      "genai",
      "healthcare",
      "portfolio-featured"
    ],
    "html_url": "https://github.com/gderamchi/hackathon_doctolib",
    "homepage": null,
    "stars": 2,
    "language": "Python",
    "updated": "2025-06-02T10:32:22Z"
  },
  {
    "name": "2024-2025-project-3-quickest-path-team-7",
    "title": "Optimized Pathfinding Solution",
    "description": {
      "en": "Enhances route efficiency using C++ algorithms.",
      "fr": "Enhances route efficiency using C++ algorithms."
    },
    "date": "2025",
    "image": "src/assets/images/projects/default.webp",
    "topics": [
      "portfolio-featured",
      "C++",
      "JavaScript",
      "CSS"
    ],
    "html_url": "https://github.com/algosup/2024-2025-project-3-quickest-path-team-7",
    "homepage": null,
    "stars": 4,
    "language": "C++",
    "updated": "2025-02-25T11:24:47Z"
  },
  {
    "name": "GenAI_hackaton",
    "title": "AI Client Profile Generator",
    "description": {
      "en": "Automates client profile creation by merging public data for SFIL.",
      "fr": "Automates client profile creation by merging public data for SFIL."
    },
    "date": "2025",
    "image": "src/assets/images/projects/default.webp",
    "topics": [
      "Python",
      "CSS",
      "JavaScript"
    ],
    "html_url": "https://github.com/GuillotSamuel/GenAI_hackaton",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-02-04T09:27:57Z"
  },
  {
    "name": "2023-2024-project-3-virtual-processor-team-2",
    "title": "Virtual Processor Development in C",
    "description": {
      "en": "A project developing a virtual processor using C, focusing on interpreters and assembly languages.",
      "fr": "A project developing a virtual processor using C, focusing on interpreters and assembly languages."
    },
    "date": "2024",
    "image": "src/assets/images/projects/2023-2024-project-3-virtual-processor-team-2.webp",
    "topics": [
      "aop",
      "aop-interpreter",
      "asm",
      "assembly",
      "at2",
      "iat2",
      "interpreter",
      "language-model"
    ],
    "html_url": "https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2",
    "homepage": null,
    "stars": 8,
    "language": "C",
    "updated": "2025-09-25T10:23:22Z"
  },
  {
    "name": "2024-2025-project-2-serious-game-team-3",
    "title": "Green City Management Game",
    "description": {
      "en": "Build a city balancing economic growth and eco-sustainability.",
      "fr": "Build a city balancing economic growth and eco-sustainability."
    },
    "date": "2024",
    "image": "src/assets/images/projects/default.webp",
    "topics": [
      "climate-change",
      "godot",
      "godot-engine",
      "godot4",
      "portfolio-featured",
      "serious-game",
      "GDScript",
      "game"
    ],
    "html_url": "https://github.com/algosup/2024-2025-project-2-serious-game-team-3",
    "homepage": null,
    "stars": 1,
    "language": "GDScript",
    "updated": "2025-02-25T11:24:15Z"
  },
  {
    "name": "2023-2024-project-4-sportshield-team-6",
    "title": "SportShield Enhancement",
    "description": {
      "en": "Enhances Coris Innovation's sports safety product.",
      "fr": "Enhances Coris Innovation's sports safety product."
    },
    "date": "2024",
    "image": "src/assets/images/projects/2023-2024-project-4-sportshield-team-6.webp",
    "topics": [
      "C++",
      "C"
    ],
    "html_url": "https://github.com/algosup/2023-2024-project-4-sportshield-team-6",
    "homepage": null,
    "stars": 0,
    "language": "C++",
    "updated": "2024-11-18T16:45:57Z"
  },
  {
    "name": "2024-2025-project-1-fpga-team-4",
    "title": "Frogger Arcade Game Recreation on FPGA",
    "description": {
      "en": "A school project emulating the classic Frogger game on an FPGA board using Verilog.",
      "fr": "A school project emulating the classic Frogger game on an FPGA board using Verilog."
    },
    "date": "2024",
    "image": "src/assets/images/projects/2024-2025-project-1-fpga-team-4.webp",
    "topics": [
      "fpga",
      "retrogaming",
      "school-project",
      "verilog",
      "Verilog",
      "Shell",
      "game"
    ],
    "html_url": "https://github.com/algosup/2024-2025-project-1-fpga-team-4",
    "homepage": null,
    "stars": 2,
    "language": "Verilog",
    "updated": "2024-11-13T13:36:24Z"
  },
  {
    "name": "hackaton-blockchain-vierzon-2024",
    "title": "Blockchain Hackathon Platform",
    "description": {
      "en": "A platform for hosting and managing blockchain hackathons.",
      "fr": "A platform for hosting and managing blockchain hackathons."
    },
    "date": "2024",
    "image": "src/assets/images/projects/default.webp",
    "topics": [
      "JavaScript",
      "HTML",
      "Solidity"
    ],
    "html_url": "https://github.com/0xBelnadris/hackaton-blockchain-vierzon-2024",
    "homepage": null,
    "stars": 0,
    "language": "JavaScript",
    "updated": "2024-10-06T19:12:27Z"
  },
  {
    "name": "2023-2024-project-5-flutter-team-1",
    "title": "Mobile Application Development with Flutter",
    "description": {
      "en": "A cross-platform app project focused on enhancing mobile user experience.",
      "fr": "A cross-platform app project focused on enhancing mobile user experience."
    },
    "date": "2024",
    "image": "src/assets/images/projects/2023-2024-project-5-flutter-team-1.webp",
    "topics": [
      "Dart",
      "C++",
      "CMake",
      "web",
      "mobile",
      "app"
    ],
    "html_url": "https://github.com/algosup/2023-2024-project-5-flutter-team-1",
    "homepage": null,
    "stars": 1,
    "language": "Dart",
    "updated": "2024-06-20T20:00:34Z"
  },
  {
    "name": "video-game-project",
    "title": "Super Chicken Boy Game",
    "description": {
      "en": "An engaging C++ game featuring Super Chicken Boy.",
      "fr": "An engaging C++ game featuring Super Chicken Boy."
    },
    "date": "2024",
    "image": "src/assets/images/projects/default.webp",
    "topics": [
      "C++"
    ],
    "html_url": "https://github.com/JasonGROSSO/video-game-project",
    "homepage": null,
    "stars": 0,
    "language": "C++",
    "updated": "2024-04-05T11:49:23Z"
  },
  {
    "name": "2023-2024-project-2-x86-retrogaming-team-5",
    "title": "Retro Gaming on x86 Assembly",
    "description": {
      "en": "A Pac-Man game prototype built using x86 assembly and DOSBox, showcasing the potential of low-level programming.",
      "fr": "A Pac-Man game prototype built using x86 assembly and DOSBox, showcasing the potential of low-level programming."
    },
    "date": "2023",
    "image": "src/assets/images/projects/2023-2024-project-2-x86-retrogaming-team-5.webp",
    "topics": [
      "assembly",
      "assembly-x86",
      "dosbox",
      "pac-man-game",
      "portfolio-featured",
      "Assembly",
      "Batchfile",
      "ai"
    ],
    "html_url": "https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-5",
    "homepage": null,
    "stars": 0,
    "language": "Assembly",
    "updated": "2025-02-25T13:43:25Z"
  }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { projects };
}
