// Projects data - Auto-generated by sync-portfolio.js
// Last updated: 2025-12-14T00:48:12.956Z
// Total projects: 20

const projects = [
  {
    "name": "website",
    "title": "Personal Portfolio Website",
    "description": "Showcases projects, skills, and experience as a Software & AI Prompt Engineer.",
    "date": "2025",
    "image": "images/projects/website.webp",
    "topics": [
      "JavaScript",
      "CSS",
      "HTML",
      "web"
    ],
    "html_url": "https://github.com/gderamchi/website",
    "homepage": null,
    "stars": 0,
    "language": "JavaScript",
    "updated": "2025-12-13T18:02:32Z"
  },
  {
    "name": "42cursus",
    "title": "42cursus",
    "description": "42 projects",
    "date": "2025",
    "image": "images/projects/default.webp",
    "topics": [
      "C",
      "Makefile"
    ],
    "html_url": "https://github.com/gderamchi/42cursus",
    "homepage": null,
    "stars": 0,
    "language": "C",
    "updated": "2025-12-05T13:08:14Z"
  },
  {
    "name": "hack-the-gap",
    "title": "French Influencer Monitoring App",
    "description": "Analyzes influencers for trustworthiness using public data.",
    "date": "2025",
    "image": "images/projects/hack-the-gap.webp",
    "topics": [
      "TypeScript",
      "Python",
      "PLpgSQL"
    ],
    "html_url": "https://github.com/gderamchi/hack-the-gap",
    "homepage": null,
    "stars": 1,
    "language": "TypeScript",
    "updated": "2025-12-02T02:10:53Z"
  },
  {
    "name": "aurelia",
    "title": "Aurelia",
    "description": "> A sophisticated longevity strategist and women's health intelligence agent powered by AI. Combines advanced biomarker analysis, biological age estimation, and agentic research to provide personal...",
    "date": "2025",
    "image": "images/projects/default.webp",
    "topics": [
      "TypeScript",
      "Python",
      "CSS"
    ],
    "html_url": "https://github.com/slavastar/aurelia",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-11-23T10:23:20Z"
  },
  {
    "name": "HACKATHON_CND_TEAM3",
    "title": "HACKATHON CND TEAM3",
    "description": "Un système de surveillance de firewall en temps réel avec détection intelligente des menaces et suggestions de corrections automatisées.",
    "date": "2025",
    "image": "images/projects/default.webp",
    "topics": [
      "TypeScript",
      "Python",
      "JavaScript"
    ],
    "html_url": "https://github.com/hindkh21/HACKATHON_CND_TEAM3",
    "homepage": null,
    "stars": 1,
    "language": "TypeScript",
    "updated": "2025-11-20T14:23:01Z"
  },
  {
    "name": "minihack-foodtech",
    "title": "AI Vegan Diet Transition Tool",
    "description": "Helps users switch to veganism with AI dish alternatives and recipes.",
    "date": "2025",
    "image": "images/projects/minihack-foodtech.webp",
    "topics": [
      "JavaScript",
      "Shell",
      "CSS"
    ],
    "html_url": "https://github.com/gderamchi/minihack-foodtech",
    "homepage": "https://minihack-foodtech.vercel.app",
    "stars": 0,
    "language": "JavaScript",
    "updated": "2025-11-01T15:13:11Z"
  },
  {
    "name": "ai-video-maker",
    "title": "AI-Powered Photo to Video Converter",
    "description": "Transform photos into engaging videos using AI technology.",
    "date": "2025",
    "image": "images/projects/ai-video-maker.webp",
    "topics": [
      "JavaScript",
      "CSS",
      "HTML"
    ],
    "html_url": "https://github.com/gderamchi/ai-video-maker",
    "homepage": "https://ai-video-maker-hazel.vercel.app",
    "stars": 0,
    "language": "JavaScript",
    "updated": "2025-10-27T23:20:47Z"
  },
  {
    "name": "hackathonblackbox42",
    "title": "AI Code Review Bot",
    "description": "Automates code analysis and bug detection with interactive AI support.",
    "date": "2025",
    "image": "images/projects/hackathonblackbox42.webp",
    "topics": [
      "Python",
      "Shell",
      "ai"
    ],
    "html_url": "https://github.com/gderamchi/hackathonblackbox42",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-10-26T01:25:52Z"
  },
  {
    "name": "landing-page",
    "title": "User-Friendly Landing Page Design",
    "description": "Creates engaging landing pages to enhance user experience.",
    "date": "2025",
    "image": "images/projects/landing-page.webp",
    "topics": [],
    "html_url": "https://github.com/gderamchi/landing-page",
    "homepage": null,
    "stars": 0,
    "language": "Unknown",
    "updated": "2025-10-25T03:13:16Z"
  },
  {
    "name": "startup-idea",
    "title": "AI Feedback to Task Converter",
    "description": "Transforms creative feedback into tasks, cutting revision time by 50%.",
    "date": "2025",
    "image": "images/projects/startup-idea.webp",
    "topics": [
      "Python",
      "Makefile",
      "TypeScript"
    ],
    "html_url": "https://github.com/gderamchi/startup-idea",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-10-24T03:11:06Z"
  },
  {
    "name": "portfolio-florid",
    "title": "Art Portfolio Showcase",
    "description": "A modern React site displaying an art student's creations.",
    "date": "2025",
    "image": "images/projects/portfolio-florid.webp",
    "topics": [
      "TypeScript",
      "CSS",
      "HTML",
      "web"
    ],
    "html_url": "https://github.com/gderamchi/portfolio-florid",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-06-27T23:27:42Z"
  },
  {
    "name": "eugeniackathon",
    "title": "Slack Workflow Automation",
    "description": "Automates Slack tasks using webhooks and an AI agent.",
    "date": "2025",
    "image": "images/projects/eugeniackathon.webp",
    "topics": [],
    "html_url": "https://github.com/gderamchi/eugeniackathon",
    "homepage": null,
    "stars": 0,
    "language": "Unknown",
    "updated": "2025-06-04T04:21:30Z"
  },
  {
    "name": "hackathon_doctolib",
    "title": "AI Pathology Copilot",
    "description": "Enhances healthcare diagnostics using AI for pathology insights.",
    "date": "2025",
    "image": "images/projects/hackathon_doctolib.webp",
    "topics": [
      "ai",
      "aiagent",
      "backend",
      "doctolib",
      "front-end-development",
      "genai",
      "healthcare",
      "portfolio-featured"
    ],
    "html_url": "https://github.com/gderamchi/hackathon_doctolib",
    "homepage": null,
    "stars": 2,
    "language": "Python",
    "updated": "2025-06-02T10:32:22Z"
  },
  {
    "name": "telecomParisHackathon",
    "title": "Cardiac Toxicity Predictor",
    "description": "Predicts cardiac toxicity using SMILES data, enhancing drug safety assessments.",
    "date": "2025",
    "image": "images/projects/telecomParisHackathon.webp",
    "topics": [
      "Python",
      "Shell",
      "Dockerfile"
    ],
    "html_url": "https://github.com/gderamchi/telecomParisHackathon",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-05-25T20:07:57Z"
  },
  {
    "name": "telecom-hackathon-data",
    "title": "Telecom Hackathon Data",
    "description": "This project predicts hERG channel inhibition (cardiac toxicity) in molecules using machine learning.",
    "date": "2025",
    "image": "images/projects/telecom-hackathon-data.webp",
    "topics": [
      "Python",
      "Jupyter Notebook"
    ],
    "html_url": "https://github.com/gderamchi/telecom-hackathon-data",
    "homepage": null,
    "stars": 0,
    "language": "Python",
    "updated": "2025-05-24T14:32:07Z"
  },
  {
    "name": "truth-stake-social",
    "title": "Social Media Truth Verification Tool",
    "description": "Verifies facts on social media to combat misinformation.",
    "date": "2025",
    "image": "images/projects/truth-stake-social.webp",
    "topics": [
      "TypeScript",
      "CSS",
      "HTML"
    ],
    "html_url": "https://github.com/gderamchi/truth-stake-social",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-05-18T11:41:34Z"
  },
  {
    "name": "creditmanagement",
    "title": "Smart Construction Assistant",
    "description": "AI tool for organizing and analyzing construction project emails.",
    "date": "2025",
    "image": "images/projects/creditmanagement.webp",
    "topics": [
      "JavaScript",
      "HTML"
    ],
    "html_url": "https://github.com/gderamchi/creditmanagement",
    "homepage": null,
    "stars": 0,
    "language": "JavaScript",
    "updated": "2025-04-05T13:16:32Z"
  },
  {
    "name": "docagent",
    "title": "Document Automation Platform",
    "description": "Automates document processing with NLP and generation capabilities.",
    "date": "2025",
    "image": "images/projects/docagent.webp",
    "topics": [
      "TypeScript",
      "Python",
      "Shell"
    ],
    "html_url": "https://github.com/gderamchi/docagent",
    "homepage": null,
    "stars": 0,
    "language": "TypeScript",
    "updated": "2025-03-18T14:39:56Z"
  },
  {
    "name": "2023-2024-project-3-virtual-processor-team-2",
    "title": "Virtual Processor Simulator",
    "description": "Simulates processor functions to optimize assembly code.",
    "date": "2024",
    "image": "images/projects/2023-2024-project-3-virtual-processor-team-2.webp",
    "topics": [
      "aop",
      "aop-interpreter",
      "asm",
      "assembly",
      "at2",
      "iat2",
      "interpreter",
      "language-model"
    ],
    "html_url": "https://github.com/algosup/2023-2024-project-3-virtual-processor-team-2",
    "homepage": null,
    "stars": 8,
    "language": "C",
    "updated": "2025-09-25T10:23:22Z"
  },
  {
    "name": "2023-2024-project-5-flutter-team-1",
    "title": "Candidate Adoption App",
    "description": "Connects users with political candidates for engagement and support.",
    "date": "2024",
    "image": "images/projects/2023-2024-project-5-flutter-team-1.webp",
    "topics": [
      "Dart",
      "C++",
      "CMake",
      "web",
      "mobile",
      "app"
    ],
    "html_url": "https://github.com/algosup/2023-2024-project-5-flutter-team-1",
    "homepage": null,
    "stars": 1,
    "language": "Dart",
    "updated": "2024-06-20T20:00:34Z"
  }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { projects };
}
